/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSeriesRouteImport } from './routes/_app.series'
import { Route as AppMoviesRouteImport } from './routes/_app.movies'
import { Route as AppLibrariesRouteImport } from './routes/_app.libraries'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppLibraryLibraryIdRouteImport } from './routes/_app.library.$libraryId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesRoute = AppSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesRoute = AppMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => AppRoute,
} as any)
const AppLibrariesRoute = AppLibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryLibraryIdRoute = AppLibraryLibraryIdRouteImport.update({
  id: '/library/$libraryId',
  path: '/library/$libraryId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/home': typeof AppHomeRoute
  '/libraries': typeof AppLibrariesRoute
  '/movies': typeof AppMoviesRoute
  '/series': typeof AppSeriesRoute
  '/library/$libraryId': typeof AppLibraryLibraryIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/home': typeof AppHomeRoute
  '/libraries': typeof AppLibrariesRoute
  '/movies': typeof AppMoviesRoute
  '/series': typeof AppSeriesRoute
  '/': typeof AppIndexRoute
  '/library/$libraryId': typeof AppLibraryLibraryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/libraries': typeof AppLibrariesRoute
  '/_app/movies': typeof AppMoviesRoute
  '/_app/series': typeof AppSeriesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/library/$libraryId': typeof AppLibraryLibraryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/connect'
    | '/login'
    | '/home'
    | '/libraries'
    | '/movies'
    | '/series'
    | '/library/$libraryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/connect'
    | '/login'
    | '/home'
    | '/libraries'
    | '/movies'
    | '/series'
    | '/'
    | '/library/$libraryId'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/connect'
    | '/login'
    | '/_app/home'
    | '/_app/libraries'
    | '/_app/movies'
    | '/_app/series'
    | '/_app/'
    | '/_app/library/$libraryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  ConnectRoute: typeof ConnectRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/series': {
      id: '/_app/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof AppSeriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies': {
      id: '/_app/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof AppMoviesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/libraries': {
      id: '/_app/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof AppLibrariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/$libraryId': {
      id: '/_app/library/$libraryId'
      path: '/library/$libraryId'
      fullPath: '/library/$libraryId'
      preLoaderRoute: typeof AppLibraryLibraryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppLibrariesRoute: typeof AppLibrariesRoute
  AppMoviesRoute: typeof AppMoviesRoute
  AppSeriesRoute: typeof AppSeriesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLibraryLibraryIdRoute: typeof AppLibraryLibraryIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppLibrariesRoute: AppLibrariesRoute,
  AppMoviesRoute: AppMoviesRoute,
  AppSeriesRoute: AppSeriesRoute,
  AppIndexRoute: AppIndexRoute,
  AppLibraryLibraryIdRoute: AppLibraryLibraryIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  ConnectRoute: ConnectRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
