<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LumaRelay.PlayerBridge</AssemblyName>
    <DebugType>embedded</DebugType>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <OutputType>Exe</OutputType>
    <RootNamespace>LumaRelay.PlayerBridge</RootNamespace>
    <TargetFrameworks>net8.0;net8.0-windows10.0.19041.0</TargetFrameworks>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows10.0.19041.0'">
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <OutputType>WinExe</OutputType>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
